### PR TITLE
Remove node-fetch and its typings

### PR DESCRIPTION
**Pull request by Protonull**

### CODE REVIEW

**Comment by Huskydog9988** [comment]
Can't we replace this with the native fetch api node introduced?

**Comment by Gjum** [comment]
Some distros don't make it easy to use a recent nodejs, but if we require a recent nodejs for other features anyway we can switch to builtin fetch. Are there any benefits from using the builtin fetch vs node-fetch 2?

**Comment by Huskydog9988** [comment]
Not really sure to be honest, and personally I just use Docker so nose versions don't affect me much.

**Comment by Protonull** [comment]
Just tested and node 18 has native fetch, so the module shouldn't be necessary anymore

**Comment by Protonull** [comment]
All good now, this is now a 'yeet node-fetch' PR

**Comment by Huskydog9988** [comment]
I assume this is tested?

**Comment by Protonull** [comment]
> I assume this is tested?

```
$ node --version
v18.17.1
```

```js
// test.js
fetch("https://github.com/CivPlatform/map-sync/pull/67")
    .then((res) => res.text())
    .then((txt) => console.log("SUCCESS!"))
    .catch((err) => console.error("Err!", err))
```

```
$ node test.js
SUCCESS!
```

**Comment by Huskydog9988** [comment]
Good enough for me!

**Review by Huskydog9988 — APPROVED** [review]

**Pull request merged**
