### PR TITLE
chore: Add prettier autoscripts

### PR DESCRIPTION
**Pull request by specificlanguage**
Literally just doing this so we don't have to start yelling people to do this anymore and all our editors will be the same, slightly inspired by #51 

The server builds on this merge will fail but that's fiiiiiiiiiiiine. The TLDR is:
- Before building, reviewers should use `yarn run format` to format their code correctly
- While building, prettier will just check that files are correctly formatted.

I didn't prettier during this commit so we don't have to deal with a million merge conflicts when someone inevitably runs format

### CODE REVIEW

**Comment by Huskydog9988** [comment]
You could also just make it a github action, I've used [this one](https://github.com/marketplace/actions/prettier-action) in the past.

**Comment by Gjum** [comment]
sooo ... it works as far as detecting misformatted code, but at the same time the build fails which is bad :laughing: 

```
Checking formatting...
[warn] src/cli.ts
[warn] src/db.ts
[warn] src/main.ts
[warn] src/MapChunk.ts
[warn] src/metadata.ts
[warn] src/protocol/HandshakePacket.ts
[warn] src/protocol/index.ts
[warn] src/protocol/RegionCatchupPacket.ts
[warn] src/protocol/RegionTimestampsPacket.ts
[warn] src/Renderer.ts
[warn] src/server.ts
[warn] src/utilities.ts
[warn] Code style issues found in [12](https://github.com/CivPlatform/map-sync/runs/7084600041?check_suite_focus=true#step:5:13) files. Forgot to run Prettier?
error Command failed with exit code 1.
```

**Comment by specificlanguage** [comment]
Ok it works now because i ran `yarn run format` lol

I did change the formatting just a bit to Prettier recommended settings, namely, `tabWidth: 4` but honestly it's whatever we can change settings if we need to

**Comment by Gjum** [comment]
merge conflicts, as expected :glad:

**Pull request merged**
